from mininet.topo import Topo

class Mytopo(Topo):
    def __init__(self):
        Topo.__init__(self)
        host1=self.addHost("h1")
        host2=self.addHost("h2")
        h3=self.addHost("h3")
        s1=self.addSwitch("s1")
        s2=self.addSwitch("s2")
        s3=self.addSwitch("s3")
        s4=self.addSwitch("s4")
        s5=self.addSwitch("s5")
        s6=self.addSwitch("s6")
        s7=self.addSwitch("s7")
        s8=self.addSwitch("s8")
        s9=self.addSwitch("s9")
        s10=self.addSwitch("s10")
        s11=self.addSwitch("s11")
        s12=self.addSwitch("s12")
        s13=self.addSwitch("s13")
        s14=self.addSwitch("s14")
        self.addLink(host1,s1)
        self.addLink(s1,s2)
        self.addLink(s3,s2)
        self.addLink(s3,s4)
        self.addLink(s4,s6)
        self.addLink(s5,s2)
        self.addLink(s5,s6)
        self.addLink(s5,s13)
        self.addLink(s6,s8)
        self.addLink(s6,s7)
        self.addLink(s7,s10)
        self.addLink(s8,s9)
        self.addLink(s8,s12)
        self.addLink(s9,s10)
        self.addLink(s9,s11)
        self.addLink(s11,host2)
        self.addLink(s12,s14)
        self.addLink(s12,s13)
        self.addLink(s13,s14)
        self.addLink(s14,h3)

topos={"mytopo":(lambda:Mytopo())}